<?php
namespace PhpUnitsOfMeasure;

/**
 * Physical quantities with this trait
 * have units which are metric and therefore have
 * a standard set of prefixes.
 */
trait HasIECUnitsTrait
{
    /**
     * Given the patterns for generating the names and aliases,
     * generate the various metric units of measure and add
     * them to this physical quantity.
     *
     * Names and Aliases are created by replacing identifiers in the respective
     * patterns.  The current allowed replacement identifiers are:
     *   %p = the abbreviated IEC prefix, like 'Mi' for 'mebibits' or 'Ki' for 'kibibits'
     *   %P = the full IEC prefix, like 'mebi' for 'mebibits' or 'kibi' for 'kibibits'
     *   %U = uppercase version of %P
     *
     * So for instance, in order to generate 'kg', 'mg', and 'g' names for IEC units, the
     * appropriate pattern would be '%pg'.  Similarly, to generate 'kilogram', 'milligram',
     * and 'gram' aliases, the pattern would be '%Pgram'.
     *
     * The $iecUnit given in the 1st parameter must be some IEC unit in the series of units
     * to be generated by this method.  This value is necessary to establish a conversion
     * factor between this continuum of IEC units and the Physical Quantity's native unit.
     *
     * The second parameter provides a scaling factor between the given IEC unit in the first parameter
     * and the base unit of the IEC continuum (ie, 'grams', 'meters', 'seconds', etc).  For instance,
     * if a Kilogram unit of measure was passed for the 1st parameter, it would be necessary to
     * then pass 1e-3 in the 2nd parameter to indicate that a gram is 1/1000 of the given unit.
     *
     * @param  UnitOfMeasure $iecUnit             A unit in this physical quantity that is an IEC unit of measure
     * @param float          $toBaseIecUnitFactor The power-of-ten factor that converts the given IEC unit into the not-prefixed IEC base unit (ie 1e-3 for kilograms)
     * @param string         $namePattern         The pattern to apply to the base unit's name to generate a new IEC unit name
     * @param array          $aliasPatterns       The collection of alias patterns to use in generating a new IEC unit's aliases
     * @param integer|null   $siBase              Used base for si units (1000 or 1024)
     */
    protected static function addMissingIECPrefixedUnits(
        UnitOfMeasure $iecUnit,
        float         $toBaseIecUnitFactor,
        string        $namePattern,
        array         $aliasPatterns = [],
        int           $siBase = null
    ) {
        /**
         * The standard set of IEC prefixes
         * https://en.wikipedia.org/wiki/Binary_prefix
         */
        $iecPrefixes = [
            [
                'abbr_prefix' => 'Yi',
                'long_prefix' => 'yobi',
                'factor'      => 1208925819614629174706176 // 2^80
            ],
            [
                'abbr_prefix' => 'Zi',
                'long_prefix' => 'zebi',
                'factor'      => 1180591620717411303424 // 2^70
            ],
            [
                'abbr_prefix' => 'Ei',
                'long_prefix' => 'exbi',
                'factor'      => 1152921504606846976 // 2^60
            ],
            [
                'abbr_prefix' => 'Pi',
                'long_prefix' => 'pebi',
                'factor'      => 1125899906842624 // 2^50
            ],
            [
                'abbr_prefix' => 'Ti',
                'long_prefix' => 'tebi',
                'factor'      => 1099511627776 // 2^40
            ],
            [
                'abbr_prefix' => 'Gi',
                'long_prefix' => 'gibi',
                'factor'      => 1073741824 // 2^30
            ],
            [
                'abbr_prefix' => 'Mi',
                'long_prefix' => 'mebi',
                'factor'      => 1048576 // 2^20
            ],
            [
                'abbr_prefix' => 'Ki',
                'long_prefix' => 'kibi',
                'factor'      => 1024    // 2^10
            ],

            // Partial list of SI prefixes (not all used for storages)
            [
                'abbr_prefix' => 'Y',
                'long_prefix' => 'yotta',
                'factor'      => 1e24,
                'si'          => 8
            ],
            [
                'abbr_prefix' => 'Z',
                'long_prefix' => 'zetta',
                'factor'      => 1e21,
                'si'          => 7
            ],
            [
                'abbr_prefix' => 'E',
                'long_prefix' => 'exa',
                'factor'      => 1e18,
                'si'          => 6
            ],
            [
                'abbr_prefix' => 'P',
                'long_prefix' => 'peta',
                'factor'      => 1e15,
                'si'          => 5
            ],
            [
                'abbr_prefix' => 'T',
                'long_prefix' => 'tera',
                'factor'      => 1e12,
                'si'          => 4
            ],
            [
                'abbr_prefix' => 'G',
                'long_prefix' => 'giga',
                'factor'      => 1e9,
                'si'          => 3
            ],
            [
                'abbr_prefix' => 'M',
                'long_prefix' => 'mega',
                'factor'      => 1e6,
                'si'          => 2
            ],
            [
                'abbr_prefix' => 'k',
                'long_prefix' => 'kilo',
                'factor'      => 1e3,
                'si'          => 1
            ],

            [
                'abbr_prefix' => '',
                'long_prefix' => '',
                'factor'      => 1
            ],
        ];

        // Determine the conversion factor from the no-prefix IEC unit to the physical quantity's native unit
        $noPrefixToNativeUnitFactor = $iecUnit->convertValueToNativeUnitOfMeasure(1) * $toBaseIecUnitFactor;

        // For each of the standard IEC prefixes, attempt to register a new unit of measure
        foreach ($iecPrefixes as $prefixDefinition) {
            // Build a function for resolving a pattern into a unit name
            $parsePattern = function ($pattern) use ($prefixDefinition) {
                return strtr(
                    $pattern,
                    [
                        '%p' => $prefixDefinition['abbr_prefix'],
                        '%P' => $prefixDefinition['long_prefix'],
                        '%U' => strtoupper($prefixDefinition['long_prefix'])
                    ]
                );
            };

            // Generate the base name of the new unit
            $name = $parsePattern($namePattern);

            // Determine the factor that converts the new unit into the physical quantity's
            //   native unit of measure.
            if ($siBase === 1024 && isset($prefixDefinition['si'])) {
                $prefixDefinition['factor'] = 1024 ** $prefixDefinition['si'];
            }
            $toNativeUnitFactor = $noPrefixToNativeUnitFactor * $prefixDefinition['factor'];

            // Instantiate the new unit of measure
            $newUnit = UnitOfMeasure::linearUnitFactory($name, $toNativeUnitFactor);

            // Generate the aliases of the new unit
            foreach ($aliasPatterns as $aliasPattern) {
                $newUnitAlias = $parsePattern($aliasPattern);
                $newUnit->addAlias($newUnitAlias);
            }

            // If the unit doesn't conflict with any of the already-existing units, register it
            if (!static::unitNameOrAliasesAlreadyRegistered($newUnit)) {
                static::addUnit($newUnit);
            }
        }
    }
}
